export const COUNTRY_TEXT_CONFIG = {
    COUNTRY_PAGE_HEADER: 'Country management',
    COUNTRY_NAME_FIELD_LBL: 'Name',
    COUNTRY_CODE_FIELD_LBL: 'Code',
    COUNTRY_STATUS_FIELD_LBL: 'Status',
    COUNTRY_SEARCH_HEADER_LBL: 'Search Criteria',
    COUNTRY_TOTAL_LBL: 'Countries',
    COUNTRY_CREATE_HEADER_LBL: 'Add New Country',
    COUNTRY_UPDATE_HEADER_LBL: 'Update Country',
    COUNTRY_SEARCH_BTN: 'Search',
    COUNTRY_ADD_BTN: "Add new",
    COUNTRY_RESET_BTN: 'Reset',
    COUNTRY_SUBMIT_BTN: 'Submit',
    COUNTRY_CLOSE_BTN: 'Close',
    CREATE_COUNTRY_SUCCESS_MSG: 'The country created successfully.',
    UPDATE_COUNTRY_SUCCESS_MSG: 'The country updated successfully.',
    DELETE_COUNTRY_SUCCESS_MSG: 'The country deleted successfully.',
    CREATE_COUNTRY_DUPLICATE_MSG: 'The country exists.',
    UPDATE_COUNTRY_FAILED_MSG: 'The country updated failed.',
    DELETE_COUNTRY_FAILED_MSG: 'The country deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}