
const COUNTRY_FETCHING = 'COUNTRY_FETCHING';
const COUNTRY_FETCH_SUCCESS = 'COUNTRY_FETCH_SUCCESS';
const COUNTRY_FETCH_ERROR = 'COUNTRY_FETCH_ERROR';
const COUNTRY_MODAL_SHOW = 'COUNTRY_MODAL_SHOW';
const COUNTRY_MODAL_CLOSE = 'COUNTRY_MODAL_CLOSE';
const COUNTRY_SAVING = 'COUNTRY_SAVING';
const COUNTRY_SAVE_SUCCESS = 'COUNTRY_SAVE_SUCCESS';
const COUNTRY_SAVE_FAILED = 'COUNTRY_SAVE_FAILED';
const COUNTRY_DELETED_SUCCESS = 'COUNTRY_DELETED_SUCCESS';

export default {
    COUNTRY_FETCHING,
    COUNTRY_FETCH_SUCCESS,
    COUNTRY_FETCH_ERROR,
    COUNTRY_MODAL_SHOW,
    COUNTRY_MODAL_CLOSE,
    COUNTRY_SAVING,
    COUNTRY_SAVE_SUCCESS,
    COUNTRY_SAVE_FAILED,
    COUNTRY_DELETED_SUCCESS
}