export const ROOM_NAME_TEXT_CONFIG = {
    ROOM_NAME_PAGE_HEADER: 'Room name management',
    ROOM_NAME_NAME_FIELD_LBL: 'Name',
    ROOM_NAME_DESCRIPTION_FIELD_LBL: 'Description',
    ROOM_NAME_ROOM_TYPE_FIELD_LBL: 'RoomType',
    ROOM_NAME_STATUS_FIELD_LBL: 'Status',
    ROOM_NAME_SEARCH_HEADER_LBL: 'Search Criteria',
    ROOM_NAME_TOTAL_LBL: 'RoomNames',
    ROOM_NAME_CREATE_HEADER_LBL: 'Add New Room name',
    ROOM_NAME_UPDATE_HEADER_LBL: 'Update Room name',
    ROOM_NAME_SEARCH_BTN: 'Search',
    ROOM_NAME_ADD_BTN: "Add new",
    ROOM_NAME_RESET_BTN: 'Reset',
    ROOM_NAME_SUBMIT_BTN: 'Submit',
    ROOM_NAME_CLOSE_BTN: 'Close',
    CREATE_ROOM_NAME_SUCCESS_MSG: 'The Room name created successfully.',
    UPDATE_ROOM_NAME_SUCCESS_MSG: 'The Room name updated successfully.',
    DELETE_ROOM_NAME_SUCCESS_MSG: 'The Room name deleted successfully.',
    CREATE_ROOM_NAME_DUPLICATE_MSG: 'The Room name exists.',
    UPDATE_ROOM_NAME_FAILED_MSG: 'The Room name updated failed.',
    DELETE_ROOM_NAME_FAILED_MSG: 'The Room name deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}