const ROOM_NAME_FETCHING = 'ROOM_NAME_FETCHING';
const ROOM_NAME_FETCH_SUCCESS='ROOM_NAME_FETCH_SUCCESS';
const ROOM_NAME_FETCH_ERROR='ROOM_NAME_FETCH_ERROR';
const ROOM_NAME_MODAL_SHOW='ROOM_NAME_MODAL_SHOW';
const ROOM_NAME_MODAL_CLOSE='ROOM_NAME_MODAL_CLOSE';
const ROOM_NAME_SAVING='ROOM_NAME_SAVING';
const ROOM_NAME_SAVE_SUCCESS='ROOM_NAME_SAVE_SUCCESS';
const ROOM_NAME_SAVE_FAILED='ROOM_NAME_SAVE_FAILED';
const ROOM_NAME_DELETED_SUCCESS='ROOM_NAME_DELETED_SUCCESS';
const GET_ROOM_TYPE_SUCCESS='GET_ROOM_TYPE_SUCCESS';
const GET_ROOM_TYPE_ERROR='GET_ROOM_TYPE_ERROR';

export default {
    ROOM_NAME_FETCHING,
    ROOM_NAME_FETCH_SUCCESS,
    ROOM_NAME_FETCH_ERROR,
    ROOM_NAME_MODAL_SHOW,
    ROOM_NAME_MODAL_CLOSE,
    ROOM_NAME_SAVING,
    ROOM_NAME_SAVE_SUCCESS,
    ROOM_NAME_SAVE_FAILED,
    ROOM_NAME_DELETED_SUCCESS,
    GET_ROOM_TYPE_SUCCESS,
    GET_ROOM_TYPE_ERROR
}