export const CITY_TEXT_CONFIG = {
    CITY_PAGE_HEADER: 'City management',
    CITY_NAME_FIELD_LBL: 'Name',
    CITY_COUNTRYID_FIELD_LBL: 'CountryId',
    CITY_STATUS_FIELD_LBL: 'Status',
    CITY_SEARCH_HEADER_LBL: 'Search Criteria',
    CITY_TOTAL_LBL: 'Cities',
    CITY_CREATE_HEADER_LBL: 'Add New City',
    CITY_UPDATE_HEADER_LBL: 'Update City',
    CITY_SEARCH_BTN: 'Search',
    CITY_ADD_BTN: "Add new",
    CITY_RESET_BTN: 'Reset',
    CITY_SUBMIT_BTN: 'Submit',
    CITY_CLOSE_BTN: 'Close',
    CREATE_CITY_SUCCESS_MSG: 'The city created successfully.',
    UPDATE_CITY_SUCCESS_MSG: 'The city updated successfully.',
    DELETE_CITY_SUCCESS_MSG: 'The city deleted successfully.',
    CREATE_CITY_DUPLICATE_MSG: 'The city exists.',
    UPDATE_CITY_FAILED_MSG: 'The city updated failed.',
    DELETE_CITY_FAILED_MSG: 'The city deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}