
const CITY_FETCHING = 'CITY_FETCHING';
const CITY_FETCH_SUCCESS = 'CITY_FETCH_SUCCESS';
const CITY_FETCH_ERROR = 'CITY_FETCH_ERROR';
const CITY_MODAL_SHOW = 'CITY_MODAL_SHOW';
const CITY_MODAL_CLOSE = 'CITY_MODAL_CLOSE';
const CITY_SAVING = 'CITY_SAVING';
const CITY_SAVE_SUCCESS = 'CITY_SAVE_SUCCESS';
const CITY_SAVE_FAILED = 'CITY_SAVE_FAILED';
const CITY_DELETED_SUCCESS = 'CITY_DELETED_SUCCESS';
const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
const GET_COUNTRY_ERROR = 'GET_COUNTRY_ERROR';

export default {
    CITY_FETCHING,
    CITY_FETCH_SUCCESS,
    CITY_FETCH_ERROR,
    CITY_MODAL_SHOW,
    CITY_MODAL_CLOSE,
    CITY_SAVING,
    CITY_SAVE_SUCCESS,
    CITY_SAVE_FAILED,
    CITY_DELETED_SUCCESS,
    GET_COUNTRY_SUCCESS,
    GET_COUNTRY_ERROR
}