export const AMENITY_CATEGORY_TEXT_CONFIG = {
    AMENITY_CATEGORY_PAGE_HEADER: 'Amenity Category management',
    AMENITY_CATEGORY_NAME_FIELD_LBL: 'Name',
    AMENITY_CATEGORY_DESCRIPTION_FIELD_LBL: 'Description',
    AMENITY_CATEGORY_STATUS_FIELD_LBL: 'Status',
    AMENITY_CATEGORY_SEARCH_HEADER_LBL: 'Search Criteria',
    AMENITY_CATEGORY_TOTAL_LBL: 'AmenityCategories',
    AMENITY_CATEGORY_CREATE_HEADER_LBL: 'Add New Amenity Category',
    AMENITY_CATEGORY_UPDATE_HEADER_LBL: 'Update Amenity Category',
    AMENITY_CATEGORY_SEARCH_BTN: 'Search',
    AMENITY_CATEGORY_ADD_BTN: "Add new",
    AMENITY_CATEGORY_RESET_BTN: 'Reset',
    AMENITY_CATEGORY_SUBMIT_BTN: 'Submit',
    AMENITY_CATEGORY_CLOSE_BTN: 'Close',
    CREATE_AMENITY_CATEGORY_SUCCESS_MSG: 'The Amenity Category created successfully.',
    UPDATE_AMENITY_CATEGORY_SUCCESS_MSG: 'The Amenity Category updated successfully.',
    DELETE_AMENITY_CATEGORY_SUCCESS_MSG: 'The Amenity Category deleted successfully.',
    CREATE_AMENITY_CATEGORY_DUPLICATE_MSG: 'The Amenity Category exists.',
    UPDATE_AMENITY_CATEGORY_FAILED_MSG: 'The Amenity Category updated failed.',
    DELETE_AMENITY_CATEGORY_FAILED_MSG: 'The Amenity Category deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}