const AMENITY_CATEGORY_FETCHING = 'AMENITY_CATEGORY_FETCHING';
const AMENITY_CATEGORY_FETCH_SUCCESS = 'AMENITY_CATEGORY_FETCH_SUCCESS';
const AMENITY_CATEGORY_FETCH_ERROR = 'AMENITY_CATEGORY_FETCH_ERROR';
const AMENITY_CATEGORY_MODAL_SHOW = 'AMENITY_CATEGORY_MODAL_SHOW';
const AMENITY_CATEGORY_MODAL_CLOSE = 'AMENITY_CATEGORY_MODAL_CLOSE';
const AMENITY_CATEGORY_SAVING = 'AMENITY_CATEGORY_SAVING';
const AMENITY_CATEGORY_SAVE_SUCCESS = 'AMENITY_CATEGORY_SAVE_SUCCESS';
const AMENITY_CATEGORY_SAVE_FAILED = 'AMENITY_CATEGORY_SAVE_FAILED';
const AMENITY_CATEGORY_DELETED_SUCCESS = 'AMENITY_CATEGORY_DELETED_SUCCESS';

export default {
    AMENITY_CATEGORY_FETCHING,
    AMENITY_CATEGORY_FETCH_SUCCESS,
    AMENITY_CATEGORY_FETCH_ERROR,
    AMENITY_CATEGORY_MODAL_SHOW,
    AMENITY_CATEGORY_MODAL_CLOSE,
    AMENITY_CATEGORY_SAVING,
    AMENITY_CATEGORY_SAVE_SUCCESS,
    AMENITY_CATEGORY_SAVE_FAILED,
    AMENITY_CATEGORY_DELETED_SUCCESS
}