export const ROOMTYPE_TEXT_CONFIG = {
    ROOMTYPE_PAGE_HEADER: 'Room Type management',
    ROOMTYPE_NAME_FIELD_LBL: 'Name',
    ROOMTYPE_DESCRIPTION_FIELD_LBL: 'Description',
    ROOMTYPE_STATUS_FIELD_LBL: 'Status',
    ROOMTYPE_SEARCH_HEADER_LBL: 'Search Criteria',
    ROOMTYPE_TOTAL_LBL: 'RoomTypes',
    ROOMTYPE_CREATE_HEADER_LBL: 'Add New Room Type',
    ROOMTYPE_UPDATE_HEADER_LBL: 'Update Room Type',
    ROOMTYPE_SEARCH_BTN: 'Search',
    ROOMTYPE_ADD_BTN: "Add new",
    ROOMTYPE_RESET_BTN: 'Reset',
    ROOMTYPE_SUBMIT_BTN: 'Submit',
    ROOMTYPE_CLOSE_BTN: 'Close',
    CREATE_ROOMTYPE_SUCCESS_MSG: 'The Room Type created successfully.',
    UPDATE_ROOMTYPE_SUCCESS_MSG: 'The Room Type updated successfully.',
    DELETE_ROOMTYPE_SUCCESS_MSG: 'The Room Type deleted successfully.',
    CREATE_ROOMTYPE_DUPLICATE_MSG: 'The Room Type exists.',
    UPDATE_ROOMTYPE_FAILED_MSG: 'The Room Type updated failed.',
    DELETE_ROOMTYPE_FAILED_MSG: 'The Room Type deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}