export const ROOM_TYPE_TEXT_CONFIG = {
    ROOM_TYPE_PAGE_HEADER: 'Room Type management',
    ROOM_TYPE_NAME_FIELD_LBL: 'Name',
    ROOM_TYPE_DESCRIPTION_FIELD_LBL: 'Description',
    ROOM_TYPE_STATUS_FIELD_LBL: 'Status',
    ROOM_TYPE_SEARCH_HEADER_LBL: 'Search Criteria',
    ROOM_TYPE_TOTAL_LBL: 'RoomTypes',
    ROOM_TYPE_CREATE_HEADER_LBL: 'Add New Room Type',
    ROOM_TYPE_UPDATE_HEADER_LBL: 'Update Room Type',
    ROOM_TYPE_SEARCH_BTN: 'Search',
    ROOM_TYPE_ADD_BTN: "Add new",
    ROOM_TYPE_RESET_BTN: 'Reset',
    ROOM_TYPE_SUBMIT_BTN: 'Submit',
    ROOM_TYPE_CLOSE_BTN: 'Close',
    CREATE_ROOM_TYPE_SUCCESS_MSG: 'The Room Type created successfully.',
    UPDATE_ROOM_TYPE_SUCCESS_MSG: 'The Room Type updated successfully.',
    DELETE_ROOM_TYPE_SUCCESS_MSG: 'The Room Type deleted successfully.',
    CREATE_ROOM_TYPE_DUPLICATE_MSG: 'The Room Type exists.',
    UPDATE_ROOM_TYPE_FAILED_MSG: 'The Room Type updated failed.',
    DELETE_ROOM_TYPE_FAILED_MSG: 'The Room Type deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}