const ROOM_TYPE_FETCHING = 'ROOM_TYPE_FETCHING';
const ROOM_TYPE_FETCH_SUCCESS = 'ROOM_TYPE_FETCH_SUCCESS';
const ROOM_TYPE_FETCH_ERROR = 'ROOM_TYPE_FETCH_ERROR';
const ROOM_TYPE_MODAL_SHOW = 'ROOM_TYPE_MODAL_SHOW';
const ROOM_TYPE_MODAL_CLOSE = 'ROOM_TYPE_MODAL_CLOSE';
const ROOM_TYPE_SAVING = 'ROOM_TYPE_SAVING';
const ROOM_TYPE_SAVE_SUCCESS = 'ROOM_TYPE_SAVE_SUCCESS';
const ROOM_TYPE_SAVE_FAILED = 'ROOM_TYPE_SAVE_FAILED';
const ROOM_TYPE_DELETED_SUCCESS = 'ROOM_TYPE_DELETED_SUCCESS';

export default {
    ROOM_TYPE_FETCHING,
    ROOM_TYPE_FETCH_SUCCESS,
    ROOM_TYPE_FETCH_ERROR,
    ROOM_TYPE_MODAL_SHOW,
    ROOM_TYPE_MODAL_CLOSE,
    ROOM_TYPE_SAVING,
    ROOM_TYPE_SAVE_SUCCESS,
    ROOM_TYPE_SAVE_FAILED,
    ROOM_TYPE_DELETED_SUCCESS
}