export const BED_TEXT_CONFIG = {
    BED_PAGE_HEADER: 'Bed management',
    BED_NAME_FIELD_LBL: 'Name',
    BED_DESCRIPTION_FIELD_LBL: 'Description',
    BED_STATUS_FIELD_LBL: 'Status',
    BED_SEARCH_HEADER_LBL: 'Search Criteria',
    BED_TOTAL_LBL: 'Beds',
    BED_CREATE_HEADER_LBL: 'Add New Bed',
    BED_UPDATE_HEADER_LBL: 'Update Bed',
    BED_SEARCH_BTN: 'Search',
    BED_ADD_BTN: "Add new",
    BED_RESET_BTN: 'Reset',
    BED_SUBMIT_BTN: 'Submit',
    BED_CLOSE_BTN: 'Close',
    CREATE_BED_SUCCESS_MSG: 'The bed created successfully.',
    UPDATE_BED_SUCCESS_MSG: 'The bed updated successfully.',
    DELETE_BED_SUCCESS_MSG: 'The bed deleted successfully.',
    CREATE_BED_DUPLICATE_MSG: 'The bed exists.',
    UPDATE_BED_FAILED_MSG: 'The bed updated failed.',
    DELETE_BED_FAILED_MSG: 'The bed deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}