
const BED_FETCHING = 'BED_FETCHING';
const BED_FETCH_SUCCESS = 'BED_FETCH_SUCCESS';
const BED_FETCH_ERROR = 'BED_FETCH_ERROR';
const BED_MODAL_SHOW = 'BED_MODAL_SHOW';
const BED_MODAL_CLOSE = 'BED_MODAL_CLOSE';
const BED_SAVING = 'BED_SAVING';
const BED_SAVE_SUCCESS = 'BED_SAVE_SUCCESS';
const BED_SAVE_FAILED = 'BED_SAVE_FAILED';
const BED_DELETED_SUCCESS = 'BED_DELETED_SUCCESS';
export default {
    BED_FETCHING,
    BED_FETCH_SUCCESS,
    BED_FETCH_ERROR,
    BED_MODAL_SHOW,
    BED_MODAL_CLOSE,
    BED_SAVING,
    BED_SAVE_SUCCESS,
    BED_SAVE_FAILED,
    BED_DELETED_SUCCESS
}