export const AMENITY_TEXT_CONFIG = {
    AMENITY_PAGE_HEADER: 'Amenity management',
    AMENITY_NAME_FIELD_LBL: 'Name',
    AMENITY_DESCRIPTION_FIELD_LBL: 'Description',
    AMENITY_AMENITYCATEGORYID_FIELD_LBL: 'Amenity Category',
    AMENITY_STATUS_FIELD_LBL: 'Status',
    AMENITY_SEARCH_HEADER_LBL: 'Search Criteria',
    AMENITY_TOTAL_LBL: 'Amenities',
    AMENITY_CREATE_HEADER_LBL: 'Add New Amenity',
    AMENITY_UPDATE_HEADER_LBL: 'Update Amenity',
    AMENITY_SEARCH_BTN: 'Search',
    AMENITY_ADD_BTN: "Add new",
    AMENITY_RESET_BTN: 'Reset',
    AMENITY_SUBMIT_BTN: 'Submit',
    AMENITY_CLOSE_BTN: 'Close',
    CREATE_AMENITY_SUCCESS_MSG: 'The amenity created successfully.',
    UPDATE_AMENITY_SUCCESS_MSG: 'The amenity updated successfully.',
    DELETE_AMENITY_SUCCESS_MSG: 'The amenity deleted successfully.',
    CREATE_AMENITY_DUPLICATE_MSG: 'The amenity exists.',
    UPDATE_AMENITY_FAILED_MSG: 'The amenity updated failed.',
    DELETE_AMENITY_FAILED_MSG: 'The amenity deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}