
const AMENITY_FETCHING = 'AMENITY_FETCHING';
const AMENITY_FETCH_SUCCESS = 'AMENITY_FETCH_SUCCESS';
const AMENITY_FETCH_ERROR = 'AMENITY_FETCH_ERROR';
const AMENITY_MODAL_SHOW = 'AMENITY_MODAL_SHOW';
const AMENITY_MODAL_CLOSE = 'AMENITY_MODAL_CLOSE';
const AMENITY_SAVING = 'AMENITY_SAVING';
const AMENITY_SAVE_SUCCESS = 'AMENITY_SAVE_SUCCESS';
const AMENITY_SAVE_FAILED = 'AMENITY_SAVE_FAILED';
const AMENITY_DELETED_SUCCESS = 'AMENITY_DELETED_SUCCESS';
const GET_AMENITYCATEGORY_SUCCESS = 'GET_AMENITYCATEGORY_SUCCESS';
const GET_AMENITYCATEGORY_ERROR = 'GET_AMENITYCATEGORY_ERROR';

export default {
    AMENITY_FETCHING,
    AMENITY_FETCH_SUCCESS,
    AMENITY_FETCH_ERROR,
    AMENITY_MODAL_SHOW,
    AMENITY_MODAL_CLOSE,
    AMENITY_SAVING,
    AMENITY_SAVE_SUCCESS,
    AMENITY_SAVE_FAILED,
    AMENITY_DELETED_SUCCESS,
    GET_AMENITYCATEGORY_SUCCESS,
    GET_AMENITYCATEGORY_ERROR
}