export const BREAKFAST_TEXT_CONFIG = {
    BREAKFAST_PAGE_HEADER: 'Breakfast management',
    BREAKFAST_NAME_FIELD_LBL: 'Name',
    BREAKFAST_DESCRIPTION_FIELD_LBL: 'Description',
    BREAKFAST_STATUS_FIELD_LBL: 'Status',
    BREAKFAST_SEARCH_HEADER_LBL: 'Search Criteria',
    BREAKFAST_TOTAL_LBL: 'Breakfasts',
    BREAKFAST_CREATE_HEADER_LBL: 'Add New Breakfast',
    BREAKFAST_UPDATE_HEADER_LBL: 'Update Breakfast',
    BREAKFAST_SEARCH_BTN: 'Search',
    BREAKFAST_ADD_BTN: "Add new",
    BREAKFAST_RESET_BTN: 'Reset',
    BREAKFAST_SUBMIT_BTN: 'Submit',
    BREAKFAST_CLOSE_BTN: 'Close',
    CREATE_BREAKFAST_SUCCESS_MSG: 'The breakfast created successfully.',
    UPDATE_BREAKFAST_SUCCESS_MSG: 'The breakfast updated successfully.',
    DELETE_BREAKFAST_SUCCESS_MSG: 'The breakfast deleted successfully.',
    CREATE_BREAKFAST_DUPLICATE_MSG: 'The breakfast exists.',
    UPDATE_BREAKFAST_FAILED_MSG: 'The breakfast updated failed.',
    DELETE_BREAKFAST_FAILED_MSG: 'The breakfast deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}