
const BREAKFAST_FETCHING = 'BREAKFAST_FETCHING';
const BREAKFAST_FETCH_SUCCESS = 'BREAKFAST_FETCH_SUCCESS';
const BREAKFAST_FETCH_ERROR = 'BREAKFAST_FETCH_ERROR';
const BREAKFAST_MODAL_SHOW = 'BREAKFAST_MODAL_SHOW';
const BREAKFAST_MODAL_CLOSE = 'BREAKFAST_MODAL_CLOSE';
const BREAKFAST_SAVING = 'BREAKFAST_SAVING';
const BREAKFAST_SAVE_SUCCESS = 'BREAKFAST_SAVE_SUCCESS';
const BREAKFAST_SAVE_FAILED = 'BREAKFAST_SAVE_FAILED';
const BREAKFAST_DELETED_SUCCESS = 'BREAKFAST_DELETED_SUCCESS';
export default {
    BREAKFAST_FETCHING,
    BREAKFAST_FETCH_SUCCESS,
    BREAKFAST_FETCH_ERROR,
    BREAKFAST_MODAL_SHOW,
    BREAKFAST_MODAL_CLOSE,
    BREAKFAST_SAVING,
    BREAKFAST_SAVE_SUCCESS,
    BREAKFAST_SAVE_FAILED,
    BREAKFAST_DELETED_SUCCESS
}