export const PROPERTYTYPE_TEXT_CONFIG = {
    PROPERTYTYPE_PAGE_HEADER: 'Property Type management',
    PROPERTYTYPE_NAME_FIELD_LBL: 'Name',
    PROPERTYTYPE_DESCRIPTION_FIELD_LBL: 'Description',
    PROPERTYTYPE_PROPERTY_FIELD_LBL: 'Property',
    PROPERTYTYPE_STATUS_FIELD_LBL: 'Status',
    PROPERTYTYPE_SEARCH_HEADER_LBL: 'Search Criteria',
    PROPERTYTYPE_TOTAL_LBL: 'PropertyTypes',
    PROPERTYTYPE_CREATE_HEADER_LBL: 'Add New Property Type',
    PROPERTYTYPE_UPDATE_HEADER_LBL: 'Update Property Type',
    PROPERTYTYPE_SEARCH_BTN: 'Search',
    PROPERTYTYPE_ADD_BTN: "Add new",
    PROPERTYTYPE_RESET_BTN: 'Reset',
    PROPERTYTYPE_SUBMIT_BTN: 'Submit',
    PROPERTYTYPE_CLOSE_BTN: 'Close',
    CREATE_PROPERTYTYPE_SUCCESS_MSG: 'The Property Type created successfully.',
    UPDATE_PROPERTYTYPE_SUCCESS_MSG: 'The Property Type updated successfully.',
    DELETE_PROPERTYTYPE_SUCCESS_MSG: 'The Property Type deleted successfully.',
    CREATE_PROPERTYTYPE_DUPLICATE_MSG: 'The Property Type exists.',
    UPDATE_PROPERTYTYPE_FAILED_MSG: 'The Property Type updated failed.',
    DELETE_PROPERTYTYPE_FAILED_MSG: 'The Property Type deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}