export const PROPERTY_TYPE_TEXT_CONFIG = {
    PROPERTY_TYPE_PAGE_HEADER: 'Property Type management',
    PROPERTY_TYPE_NAME_FIELD_LBL: 'Name',
    PROPERTY_TYPE_DESCRIPTION_FIELD_LBL: 'Description',
    PROPERTY_TYPE_PROPERTY_FIELD_LBL: 'Property',
    PROPERTY_TYPE_STATUS_FIELD_LBL: 'Status',
    PROPERTY_TYPE_SEARCH_HEADER_LBL: 'Search Criteria',
    PROPERTY_TYPE_TOTAL_LBL: 'PropertyTypes',
    PROPERTY_TYPE_CREATE_HEADER_LBL: 'Add New Property Type',
    PROPERTY_TYPE_UPDATE_HEADER_LBL: 'Update Property Type',
    PROPERTY_TYPE_SEARCH_BTN: 'Search',
    PROPERTY_TYPE_ADD_BTN: "Add new",
    PROPERTY_TYPE_RESET_BTN: 'Reset',
    PROPERTY_TYPE_SUBMIT_BTN: 'Submit',
    PROPERTY_TYPE_CLOSE_BTN: 'Close',
    CREATE_PROPERTY_TYPE_SUCCESS_MSG: 'The Property Type created successfully.',
    UPDATE_PROPERTY_TYPE_SUCCESS_MSG: 'The Property Type updated successfully.',
    DELETE_PROPERTY_TYPE_SUCCESS_MSG: 'The Property Type deleted successfully.',
    CREATE_PROPERTY_TYPE_DUPLICATE_MSG: 'The Property Type exists.',
    UPDATE_PROPERTY_TYPE_FAILED_MSG: 'The Property Type updated failed.',
    DELETE_PROPERTY_TYPE_FAILED_MSG: 'The Property Type deleted failed.',
    REQUIRED_FIELD_MSG: 'This is required field.',
}