const PROPERTY_TYPE_FETCHING = 'PROPERTY_TYPE_FETCHING';
const PROPERTY_TYPE_FETCH_SUCCESS='PROPERTY_TYPE_FETCH_SUCCESS';
const PROPERTY_TYPE_FETCH_ERROR='PROPERTY_TYPE_FETCH_ERROR';
const PROPERTY_TYPE_MODAL_SHOW='PROPERTY_TYPE_MODAL_SHOW';
const PROPERTY_TYPE_MODAL_CLOSE='PROPERTY_TYPE_MODAL_CLOSE';
const PROPERTY_TYPE_SAVING='PROPERTY_TYPE_SAVING';
const PROPERTY_TYPE_SAVE_SUCCESS='PROPERTY_TYPE_SAVE_SUCCESS';
const PROPERTY_TYPE_SAVE_FAILED='PROPERTY_TYPE_SAVE_FAILED';
const PROPERTY_TYPE_DELETED_SUCCESS='PROPERTY_TYPE_DELETED_SUCCESS';
const GET_PROPERTY_SUCCESS='GET_PROPERTY_SUCCESS';
const GET_PROPERTY_ERROR='GET_PROPERTY_ERROR';

export default {
    PROPERTY_TYPE_FETCHING,
    PROPERTY_TYPE_FETCH_SUCCESS,
    PROPERTY_TYPE_FETCH_ERROR,
    PROPERTY_TYPE_MODAL_SHOW,
    PROPERTY_TYPE_MODAL_CLOSE,
    PROPERTY_TYPE_SAVING,
    PROPERTY_TYPE_SAVE_SUCCESS,
    PROPERTY_TYPE_SAVE_FAILED,
    PROPERTY_TYPE_DELETED_SUCCESS,
    GET_PROPERTY_SUCCESS,
    GET_PROPERTY_ERROR
}