export const PROPERTY_TEXT_CONFIG = {
    PROPERTY_PAGE_HEADER: 'Property management',
    PROPERTY_NAME_FIELD_LBL: 'Name',
    PROPERTY_DESCRIPTION_FIELD_LBL: 'Description',
    PROPERTY_STATUS_FIELD_LBL: 'Status',
    PROPERTY_SEARCH_HEADER_LBL: 'Search Criteria',
    PROPERTY_TOTAL_LBL: 'Properties',
    PROPERTY_CREATE_HEADER_LBL: 'Add New Property',
    PROPERTY_UPDATE_HEADER_LBL: 'Update property',
    PROPERTY_SEARCH_BTN: 'Search',
    PROPERTY_ADD_BTN: 'Add New',
    PROPERTY_RESET_BTN: 'Reset',
    PROPERTY_SUBMIT_BTN: 'Submit',
    PROPERTY_CLOSE_BTN: 'Close',
    CREATE_PROPERTY_SUCCESS_MSG: 'The property created successfully.',
    UPDATE_PROPERTY_SUCCESS_MSG: 'The property updated successfully.',
    DELETE_PROPERTY_SUCCESS_MSG: 'The property deleted successfully.',
    CREATE_PROPERTY_DUPLICATE_MSG: 'The property exists.',
    UPDATE_PROPERTY_FAILED_MSG: 'The property update failed.',
    DELETE_PROPERTY_FAILED_MSG: 'The property delete failed.',
    REQUIRED_FIELD_MSG: 'This is required field.,'
}