const PROPERTY_FETCHING = 'PROPERTY_FETCHING';
const PROPERTY_FETCH_SUCCESS = 'PROPERTY_FETCH_SUCCESS';
const PROPERTY_FETCH_ERROR = 'PROPERTY_FETCH_ERROR';
const PROPERTY_MODAL_SHOW = 'PROPERTY_MODAL_SHOW';
const PROPERTY_MODAL_CLOSE = 'PROPERTY_MODAL_CLOSE';
const PROPERTY_SAVING = 'PROPERTY_SAVING';
const PROPERTY_SAVE_SUCCESS = 'PROPERTY_SAVE_SUCCESS';
const PROPERTY_SAVE_FAILED = 'PROPERTY_SAVE_FAILED';
const PROPERTY_DELETED_SUCCESS = 'PROPERTY_DELETED_SUCCESS';
const PROPERTY_FILE_CHANGE = 'PROPERTY_FILE_CHANGE';

export default {
    PROPERTY_FETCHING,
    PROPERTY_FETCH_SUCCESS,
    PROPERTY_FETCH_ERROR,
    PROPERTY_MODAL_SHOW,
    PROPERTY_MODAL_CLOSE,
    PROPERTY_SAVING,
    PROPERTY_SAVE_SUCCESS,
    PROPERTY_SAVE_FAILED,
    PROPERTY_DELETED_SUCCESS,
    PROPERTY_FILE_CHANGE
}