const PROPERTY_FETCHING = 'PROPERTY_FETCHING';
const PROPERTY_FETCH_SUCCESS = 'PROPERTY_FETCH_SUCCESS';
const PROPERTY_FETCH_ERROR = 'PROPERTY_FETCH_ERROR';

export default {
    PROPERTY_FETCHING,
    PROPERTY_FETCH_SUCCESS,
    PROPERTY_FETCH_ERROR
}